# Makefile for the TU58 Device Driver project - RLA [12-Aug-94]

CC=bcc -c -ms -Z -O -Ol -Oe
ASM=tasm -mx

.c.obj:
   $(CC) $<

.asm.obj:
   $(ASM) $*

lptstore.sys:   header.obj cprint.obj lptstore.obj driver.obj
   tlink -t -m -s -n header cprint lptstore driver, lptstore.sys

lptstore.com:   header.obj cprint.obj sd.obj driver.obj
   tlink -t -m -s -n header cprint lptstore driver, lptstore.sys
   rename lptstore.sys lptstore.com

clean:
   del *.obj
   del lptstore.sys
   del *.map

driver.obj: cprint.c driver.c cprint.c cprint.h standard.h driver.h lptstore.h
lptstore.obj:   lptstore.c lptstore.h standard.h driver.h
header.obj: header.asm
